#!/bin/sh
echo "*** starting vecan-dbus ***"
exec 2>&1
exec softlimit -d 100000000 -s 1000000 -a 100000000 /opt/victronenergy/vecan-dbus/vecan-dbus -c socketcan:can1 --banner --log-before 25 --log-after 25 -vv
